
all: BangBang.nxj
	nxjupload -r BangBang.nxj

BangBang.nxj: BangBang.java
	nxjc BangBang.java
	nxjlink -o BangBang.nxj BangBang

Prop: Prop.nxj
	nxjupload -r Prop.nxj

Prop.nxj: Prop.java
	nxjc Prop.java
	nxjlink -o Prop.nxj Prop


PID: PID.nxj
	nxjupload -r PID.nxj

PID.nxj: PID.java
	nxjc PID.java
	nxjlink -o PID.nxj PID
